[package]
name = "guiexample"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.30.0"
env_logger = { version = "0.10", default-features = false, features = [
    "auto-color",
    "humantime",
] }
